name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: cloudrun
          environment-file: ./ci/env.yaml
          use-mamba: true
      - name: install dependencies
        run: |
          mamba run -n cloudrun pip install -r ./src/requirements.txt
          mamba run -n cloudrun pip install -r dev-requirements.txt
      - name: list conda env
        run: |
          conda info
          conda list
      - name: run tests
        run: |
          pytest ./src/tests
